### ISSUE TITLE
tests don't compile on 1.34.0

### ISSUE THREAD

**Issue by Follpvosten** [qnighy/libwebp-image-rs#5]
While I can build the crate with `cargo +1.34.0 build` just fine, trying to test it on that version fails with this error:

```
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.6.2/src/lib.rs:45:27
   |
45 | #[cfg(feature = "alloc")] extern crate alloc;
   |                           ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `rand_core`.
```

**Comment by Follpvosten** [comment]
I just saw that the CI tests on 1.36.0, so I guess that's the MSRV for the tests. I think it would be a good idea to either change the readme and name 1.36.0 as the MSRV, or add a CI check to verify it at least compiles on 1.34.0, whichever you prefer.

**Comment by qnighy** [comment]
I still think of 1.34.0 as MSRV because if it builds, it works the same as in newer compilers in most cases. Added clarification in README though. Thanks!
